language: java

sudo: false
dist: trusty

before_install: unset _JAVA_OPTIONS

install: echo "Don't let Travis CI execute './gradlew assemble' by default"

matrix:
  include:
  - jdk: oraclejdk11
  - jdk: openjdk-ea
  allow_failures:
  - jdk: openjdk-ea

after_success:
- bash <(curl -s https://codecov.io/bash)

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
